### PR TITLE
Discrete gradient improvements

### PR DESCRIPTION
**Pull request by WetzelVictor**
Hello dear PyPHS users,

### Problem statement
@FabricioS and I had difficulties simulating a non-linear physical systems where one of the state variables takes small values around its equilibrium (approx. 1e-8 around 0). The Newton-Raphson algorithm could not converge despite a well conditioned matrix.

Eventually we located the problem at the evaluation of the discrete gradient, which sufferered from:
1. Cancellation problem when the increment on the state variable dx tends towards 0 on the finite difference approximation
2. Discontinuity at the junction between the finite difference and the continuous approximation

Here is on an example, where parts of the curve is affected by these errors:
dxH_zoom_problème_numérique_crop

### Proposed solution
The first point is solved to raise the tolerance from the machine's precision to its square root. Note that this tolerance is **problem dependent**. For instance in our physical system the tolerance has to be set at eps**0.4.

The second point it adressed by expending the continuous approximation of the gradient.

### How I tested it so far
I tested this PR on my particular problem (a non linear and conservative system).

More tests from other users should be performed.

### CODE REVIEW

**Comment by FabricioS** [comment]
Hi,
just a few (mathematical) words in complement to the description given by Victor.

Before PR #135, the alternative expression for the discrete gradient ("true" gradient evaluated at null increment, denoted $∇^d H(x, δx < ε) = ∇H(δx=0)$)  would almost never be triggered (at least with default values) or maybe only in the non-separable case (with part of increments set to zero).

Modifying the threshold (commit d7de1efa1 changing ε**2 to ε) made the switch much more common, and it may occur for increments that are not so small.Given that
∇^d H(x, δx = ε^+) ~ ∇H(x, δx=0) + ε ∇∇H(x, δx=0) + o(ε^2)
∇^d H(x, δx = ε^-) = ∇H(x, δx=0)
so that the jump is about ε ∇∇H(δx=0), i.e. non negligible.

Victor (and I) suggest to modify the alternative form to 
∇^d H(x, δx < ε) = ∇H(x, δx=0) + δx ∇∇H(x, δx=0) 
so that the jump is o(ε^2), i.e. of the order of magnitude of the machine precision.

**Comment by FabricioS** [comment]
Moreover, for readibility of the generated code (used e.g. for debug) and hopefully without performance issue, discrete gradient specification could be refactored to
`
dxhi = sympy.Piecewise((dxh0, sympy.abs(dx[i]) < numtol), (dxh, True))
`

It removes half of the lengthy finite difference expressions of the discrete gradient in C++ code.

**Comment by WetzelVictor** [comment]
Hi there,
Just noticed that I added a factor 1/2 before the  δx ∇∇H(x, δx=0) in the implementation, which is an error if I refer to @FabricioS comment above.

Can you guys confirm?

**Comment by FabricioS** [comment]
Not that trivial!
In fact, in the mathematical justification, I derived a Taylor series for the Hamiltonian gradient which lead to the expression without 1/2.
However, we here want to properly extend the discrete gradient towards small increment δx.
Due to the definition of the discrete gradient (based on a difference on Hamiltonian values, it may be more relevant to derive the Taylor series for the Hamiltonian itself
H(x+δx) = H(x) + ∇H(x).δx + 1/2 δx.∇∇H(x).δx + o(|δx|^2)
so that the discrete gradient is
∇^d H(x, δx) = (H(x+δx) - H(x)) / δx = ∇H(x) + **1/2** ∇∇H(x).δx + o(|δx|)
which proves that you did provide the correct alternative expression for small increment δx.

**Pull request merged**
