### PR TITLE
adding realizability solving functions for linear electronic graphs

### PR DESCRIPTION
**Pull request by JNaj**

### CODE REVIEW

**Comment by JNaj** [comment]
# netlist pour test
```
electronics.source Ue ('N1', '#'): type=voltage;
electronics.capacitor C1 ('N1', 'N3'): C=('C1', 1e-06);
electronics.resistor R1 ('N1', 'N2'): R=('R1', 1e-06);
electronics.capacitor C2 ('N2', 'N3'): C=('C2', 1e-06);
electronics.capacitor C3 ('N2', 'N3'): C=('C3', 1e-06);
electronics.resistor R2 ('N3', '#'): R=('R2', 1e-06);
electronics.inductor L1 ('N1', 'N4'): L=('L1', 1e-06);
electronics.resistor R3 ('N4', 'N6'): R=('R3', 1e-06);
electronics.inductor L3 ('N6', 'N7'): L=('L3', 1e-06);
electronics.inductor L4 ('N7', 'N8'): L=('L4', 1e-06);
electronics.resistor R4 ('N8', '#'): R=('R8', 1e-06);
```
# script pour test
```
import os
from pyphs import Netlist
from pyphs.graphs import realizability

path = os.path.join(os.getcwd(), 'ind.net')
netlist = Netlist(path)
graph = netlist.to_graph()
graph.split_sp()
realizability.graph_eq(graph)
```

**Comment by afalaize** [comment]
Travis tests failed.
This is to be investigated. Maybe the new sympy version is in cause...
Nevertheless, this PR is merged as it is.

**Comment by FabricioS** [comment]
Hi,
two tests are failing:

the [first one](https://travis-ci.org/pyphs/pyphs/jobs/401681463#L1030) seems to be related to the now classical "Argument is not an mpz" error (#26). There are still deepcopies made (deep) under the hood :+1: https://travis-ci.org/pyphs/pyphs/jobs/401681463#L1002

the [second one](https://travis-ci.org/pyphs/pyphs/jobs/401681463#L1054) seems due to an undetermined edge orientation. I feel non competent on this one

**Comment by afalaize** [comment]
Tests pass now with the merge of 2 new PRs: #115 and #116

**Pull request merged**
